# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :release do
    # gradle(task: 'bundleRelease')
    # Upload to internal test
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab', # Update this path if your AAB is generated in a different location
      skip_upload_apk: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_aab: false,
    )
  end
end

def get_version_code
  # This example assumes you're reading from build.gradle
  gradle_file = File.read('./android/app/build.gradle')
  match = gradle_file.match(/versionCode\s+(\d+)/)
  match[1] if match
end