# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  lane :deploy do
    version_code = get_version_code
    supply(
      version_code: version_code,
      metadata_path: './metadata/android',
      changelog: "Changelog for version #{version_code}" 
      json_key: "fastlane/persuasive-net-417001-add98881eb51.json",
      package_name: "com.gis.acegaseshms", # Replace with your app's package name
      aab: "build/app/outputs/bundle/release/app-release.aab", # or apk: "path/to/your/app.apk"
      track: "production" # or "alpha", "beta", etc.
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

def get_version_code
  # This example assumes you're reading from build.gradle
  gradle_file = File.read('./android/app/build.gradle')
  match = gradle_file.match(/versionCode\s+(\d+)/)
  match[1] if match
end